name: PinBoard
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.4.0
  faker: ^2.1.0
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/images/kakao.png
    - assets/images/link.png
    - assets/images/twitter X.png
    - assets/images/youtube.png
    - assets/images/naver.png
    - assets/images/tiktok.png